version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    container_name: nestjsapp
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:VaqjIH0ymKk2@ep-calm-bonus-a1iom3yl-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
